regex + new personality!
developedbytoby/sinerider-twitter-bot pull request #10
Opened 2023-04-14 12:37 UTC by developedbytoby

2023-04-14 14:04 UTC, grymmy requested changes
I think we also want to extract the puzzle ID with the regular expression as well.

2023-04-14 14:07 UTC, grymmy commented on app.py
>      puzzle_id = parts[0]
See where the variables "parts" and "text_parts" are above - the goal is to replace those variables, and all of the text splitting and error checking, with a simple multivariable regular expression, doing the validation all in one swoop...

2023-04-14 14:12 UTC, grymmy commented on app.py
>      puzzle_id = parts[0]
See this Stack Overflow post for more info on how one can extract multiple named regex vars: https://stackoverflow.com/questions/1800817/how-can-i-get-part-of-regex-match-as-a-variable-in-python

2023-04-15 13:14 UTC, developedbytoby commented on app.py
>      puzzle_id = parts[0]
Just updated it!

2023-04-26 14:36 UTC, grymmy approved these changes

2023-04-26 14:55 UTC, merged